### ISSUE TITLE
Feedback Request:Subnetting

### ISSUE THREAD

**Issue by yismailmo** [TechGrounds-Cloud8/cloud8-yismailmo#19]
**Feedback Request [NT06]**
Permalink to file: [[LINK]](https://github.com/TechGrounds-Cloud8/cloud8-yismailmo/blob/main/03_Cloud_1/NTW06.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
**Summary**
- Does the summary describe the subject matter fully? **yes, but I'm not sure if I entirely agree on the definition of subnets. A subnet is a specific method of splitting a network into smaller networks, but there are other options too (physical seperation or VLAN). What is the difference between those and subnets? Also I believe your CIDR notation has the meaning of the slash notation inverted.**
- Is the summary written in own words? **yes**
- Is there crucial information missing in the summary? **no**
- Is the description clear enough? **yes**

**Key Terminology**
- Are there missing key terms? **no**
- Are the key terms explained well? **yes, but see above.**

**Sources**
- Are the sources mentioned? **yes**
- Are the mentioned sources correct? **yes**

**Excercise**
(Where applicable)
- Is the result correct? **I don't know, you removed the picture lol**
- Are the experienced problems and solutions described well? **no, I think you could have been more specific what exactly was challenging**

**Comment by Killian97** [comment]
your class C explanation IP adress example is only 24 bit.
i would personnaly re read your own work and explain to your self how it works. 
i  dis agree about subnet mask. its not like a IP adress (just a hint).

and still try to make your templates a bit cleaner and easier to read

**Comment by se0727** [comment]
sunnary could have been a liitle deeper about subnetting, cidr, subnets. 
Also your drawing is not linked.
