### ISSUE TITLE
Feedback Request:IAM

### ISSUE THREAD

**Issue by yismailmo** [TechGrounds-Cloud8/cloud8-yismailmo#20]
**Feedback Request [SEC03]**
Permalink to file: [[LINK]](https://github.com/TechGrounds-Cloud8/cloud8-yismailmo/blob/main/Week_3_work/SEC03.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
i side with benbui's comment, read his and you will know what todo. your on the good path so keep going but maybe do a little more research. try to have  like a minumum of 4 sources and then combine the information you get from them

**Comment by se0727** [comment]
see above, it has to do with something one ...., somethin one ...... etc.
