### ISSUE TITLE
Feedback Request:Asymmetric encryption

### ISSUE THREAD

**Issue by yismailmo** [TechGrounds-Cloud8/cloud8-yismailmo#22]
**Feedback Request [SEC05]**
Permalink to file: [[LINK]](https://github.com/TechGrounds-Cloud8/cloud8-yismailmo/blob/main/Week_3_work/SEC05.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
looks very good, but i would explain your results a bit better. and in the into you say you shared your encryption key in ass 4, what is this key? is it a private key or a public key or a linked key or any of the others.

**Comment by benbui797** [comment]
Looks great, you have summarised everything well. I would add that once encrypted, the recipient also needs to decrypt with the sender's public key (in combination with their private key). This is what makes it safe, if you use any other key, the mathematical equation doesn't hold up and will not work. 

Also small note: after ECC: "we at UnVeil" IMO that makes it look copy/pasted
