### ISSUE TITLE
Feedback Request:Cost management and billing

### ISSUE THREAD

**Issue by yismailmo** [TechGrounds-Cloud8/cloud8-yismailmo#27]
**Feedback Request Cost management and billing**
Permalink to file: [[LINK]](https://github.com/TechGrounds-Cloud8/cloud8-yismailmo/blob/main/cloud_01/week-4-Azure-cost-mng.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by abdeslamazhir** [comment]
**Summary**
- Does the summary describe the subject matter fully? There is no summary
- Is the summary written in own words? -
- Is there crucial information missing in the summary? -
- Is the description clear enough? -

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable) Have not shown what you did and the  conditions of the Free subscription are also missing.
- Is the result correct? no
- Are the experienced problems and solutions described well?  yes
