### ISSUE TITLE
Feedback Request:Advantages of the cloud

### ISSUE THREAD

**Issue by yismailmo** [TechGrounds-Cloud8/cloud8-yismailmo#28]
**Feedback Request Advantages of the cloud**
Permalink to file: [[LINK]](https://github.com/TechGrounds-Cloud8/cloud8-yismailmo/blob/main/cloud_01/Week-4-Azure-AdvofCloud.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Acron0815** [comment]
Summary

Does the summary describe the subject matter fully? ja
Is the summary written in own words? ?
Is there crucial information missing in the summary? nee
Is the description clear enough? ja

Key Terminology
Are there missing key terms? nee
Are the key terms explained well? ja
Sources

Are the sources mentioned? ja
Are the mentioned sources correct? ja
Excercise
(Where applicable)

Is the result correct? ja
Are the experienced problems and solutions described well? ja

Clear, streamlined, and reasonably informative.
