### ISSUE TITLE
Feedback Request:Vnet

### ISSUE THREAD

**Issue by yismailmo** [TechGrounds-Cloud8/cloud8-yismailmo#35]
**Feedback Request Vnet**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-yismailmo/blob/main/Azure_cloud/week-5-Azure/Vnet.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
- Layout in assignment looks a bit messy.
- Assignment well done!

**Comment by abdeslamazhir** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? -
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? missing the terms
- Are the key terms explained well? no

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes
- Are the experienced problems and solutions described well? yes
