### ISSUE TITLE
Feedback Request:13.2 CDN

### ISSUE THREAD

**Issue by yismailmo** [TechGrounds-Cloud8/cloud8-yismailmo#39]
**Feedback Request 13.2CDN
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-yismailmo/blob/main/Azure_cloud/week-5/13..2%20Content%20Delivery%20Network%20(CDN).md)
Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by abdeslamazhir** [comment]
I do miss the explanation of some key terms like PoP, Edge server etc.. Furthermore it looks good.

**Comment by Tjomba1996** [comment]
- Layout?
- Key terms are missing
- Comparison feels a bit unstructured
