### ISSUE TITLE
Feedback Request:AzureFunctions

### ISSUE THREAD

**Issue by yismailmo** [TechGrounds-Cloud8/cloud8-yismailmo#46]
**Feedback Request Azure Functions**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-yismailmo/blob/main/Azure_cloud/week-6/AzureFunction.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
"You can easily designate an SQL and the type of trigger you want to run, which then syncs seamlessly with a text editor like VSCODE." 
I don't understand this sentence. What is the link between SQL and the function? Isn't the synchronisation with VSCode just for you to easily edit your function?

What is the benefit of using a service like this? And why would someone choose this over running a VM or containers?

**Comment by Tjomba1996** [comment]
Nice picture. Well done!
